-- MySQL Script generated by MySQL Workbench
-- 9-11-2014 22:23:58
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wuw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wuw` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wuw` ;

-- -----------------------------------------------------
-- Table `wuw`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wuw`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  `password_hash` VARCHAR(256) NOT NULL,
  `recovery_key` VARCHAR(256) NULL,
  `auth_key` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wuw`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wuw`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL,
  `img` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wuw`.`feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wuw`.`feed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL,
  `url` VARCHAR(512) NULL,
  `language_filter` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wuw`.`user_has_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wuw`.`user_has_language` (
  `user_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `language_id`),
  INDEX `fk_user_has_language_language1_idx` (`language_id` ASC),
  INDEX `fk_user_has_language_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_language_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `wuw`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_language_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `wuw`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wuw`.`feed_has_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wuw`.`feed_has_language` (
  `feed_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  PRIMARY KEY (`feed_id`, `language_id`),
  INDEX `fk_feed_has_language_language1_idx` (`language_id` ASC),
  INDEX `fk_feed_has_language_feed1_idx` (`feed_id` ASC),
  CONSTRAINT `fk_feed_has_language_feed1`
    FOREIGN KEY (`feed_id`)
    REFERENCES `wuw`.`feed` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feed_has_language_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `wuw`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
